# Generated by Django 5.2.4 on 2025-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow other signed-in users to view your profile and book collection.'),
        ),
    ]
